version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0 #localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastik:/usr/share/elasticsearch/data
    networks:
      - practica_network
    healthcheck:
      test: ["curl", "-f", "https://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
#    command: ["sysctl","-w", "vm.max_map_count=262144"]
#    sysctls:
#      vm.max_map_count: 262144

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test:
        - CMD
        - mongo
        - --eval
        - "db.adminCommand('ping')"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - practica_network

  graylog:
    image: graylog/graylog:3.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=lasMejorWebsSeHacenConTablas
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9009/
    volumes:
      - graylog:/usr/share/elasticsearch/data
    restart: on-failure
    networks:
      - practica_network
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9009:9000
      - 12201:12201
      - 12201:12201/udp
      - 1514:1514
      - 1514:1514/udp

  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - practica_network
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  wordpress:
    image: wordpress:latest
    networks:
      - practica_network
    depends_on:
      - db
    ports:
      - "9090:80"
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: primeros_logs

networks:
  practica_network:

volumes:
  wordpress:

  mysql:

  elastik:

  mongo:

  graylog:
